M48
; DRILL file {KiCad (7.0.0)} date Sun May 14 14:46:32 2023
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-05-14T14:46:32-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(7.0.0)
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0787
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0866
%
G90
G05
T1
X3.2Y-2.2
X3.2Y-4.5
X7.5Y-2.2
X7.5Y-4.5
T2
X6.9374Y-2.5268
X6.9374Y-2.8732
T0
M30
